apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
- namespace.yaml
- storm-surge-app.yaml

commonLabels:
  app.kubernetes.io/name: storm-surge
  app.kubernetes.io/part-of: oceansurge
  app.kubernetes.io/version: v1.0

images:
- name: storm-surge/frontend
  newTag: v1.0
