apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
- namespace.yaml
- deployments.yaml
- services.yaml
- configmaps.yaml
- nginx-configs.yaml
- hpa.yaml
- resource-quotas.yaml
- pod-disruption-budgets.yaml
- network-policies.yaml

labels:
- pairs:
    app.kubernetes.io/name: storm-surge
    app.kubernetes.io/part-of: oceansurge
    app.kubernetes.io/version: dev-v1.2.0
    storm-surge.io/well-architected: "compliant"

commonAnnotations:
  storm-surge.io/architecture-review: "2025-01-01"
  storm-surge.io/security-hardened: "true"

images:
- name: storm-surge/frontend
  newName: nginxinc/nginx-unprivileged
  newTag: 1.25-alpine
- name: storm-surge/product-catalog
  newName: nginxinc/nginx-unprivileged
  newTag: 1.25-alpine  
- name: storm-surge/shopping-cart
  newName: nginxinc/nginx-unprivileged
  newTag: 1.25-alpine
