apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
- namespace.yaml
- deployments.yaml
- services.yaml
- configmaps.yaml
- nginx-configs.yaml
- hpa.yaml

labels:
- pairs:
    app.kubernetes.io/name: ocean-surge
    app.kubernetes.io/part-of: oceansurge
    app.kubernetes.io/version: beta-v1.1.0

images:
- name: storm-surge/frontend
  newName: nginx
  newTag: alpine
- name: storm-surge/product-catalog
  newName: nginx
  newTag: alpine
- name: storm-surge/shopping-cart
  newName: nginx
  newTag: alpine
