apiVersion: v1
kind: ConfigMap
metadata:
  name: product-catalog-nginx
  namespace: oceansurge
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-cart-nginx
  namespace: oceansurge
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        # API endpoints for cart functionality
        location /api/ {
            root /usr/share/nginx/html;
            try_files $uri $uri/ =404;
        }
    }
