apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-surge-middleware
  namespace: storm-surge-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storm-surge-middleware
  template:
    metadata:
      labels:
        app: storm-surge-middleware
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: middleware
        image: python:3.11-slim
        command: ['/bin/bash', '-c']
        args:
        - |
          pip install flask flask-cors gunicorn
          cd /app
          gunicorn --workers 2 --bind 0.0.0.0:8000 --timeout 30 main_minimal:app
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CLUSTER_NAME
          value: "storm-surge-prod"
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: storm-surge-secrets
              key: flask-secret-key
        - name: PYTHONUNBUFFERED
          value: "1"
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: app-code
          mountPath: /app
          readOnly: true
      volumes:
      - name: app-code
        configMap:
          name: middleware-code
          defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: middleware-code
  namespace: storm-surge-prod
data:
  main_minimal.py: |
{{ .Files.Get "main_minimal.py" | indent 4 }}