apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - configmap.yaml

labels:
- pairs:
    app.kubernetes.io/name: oceansurge-middleware
    app.kubernetes.io/part-of: oceansurge
    app.kubernetes.io/version: v0.1.1
    app.kubernetes.io/component: middleware

images:
- name: oceansurge/middleware
  newName: python
  newTag: 3.11-slim

configMapGenerator:
- name: middleware-build-info
  literals:
  - BUILD_VERSION=v0.1.1
  - BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - COMPONENT=middleware
