apiVersion: v1
kind: Secret
metadata:
  name: ld-spot-secrets
  namespace: oceansurge
type: Opaque
stringData:
  ld-sdk-key: "${LAUNCHDARKLY_SDK_KEY}"
  spot-api-token: "${SPOT_API_TOKEN}"
  webhook-secret: "${WEBHOOK_SECRET}"
  # Example values - replace with real secrets:
  # ld-sdk-key: "sdk-12345678-1234-1234-1234-123456789012"
  # spot-api-token: "Bearer your-spot-api-token-here"
  # webhook-secret: "your-webhook-secret-here"
