apiVersion: v1
kind: Secret
metadata:
  name: feature-flag-secrets
  namespace: oceansurge
type: Opaque
stringData:
  # LaunchDarkly configuration
  ld-sdk-key: "${LAUNCHDARKLY_SDK_KEY}"
  # Statsig configuration
  statsig-server-key: "${STATSIG_SERVER_KEY}"
  # Common configuration
  spot-api-token: "${SPOT_API_TOKEN}"
  webhook-secret: "${WEBHOOK_SECRET}"
  # Example values - replace with real secrets:
  # ld-sdk-key: "sdk-12345678-1234-1234-1234-123456789012"
  # statsig-server-key: "secret-your-statsig-server-key-here"
  # spot-api-token: "Bearer your-spot-api-token-here"
  # webhook-secret: "your-webhook-secret-here"
