apiVersion: v1
kind: Secret
metadata:
  name: feature-flag-secrets
  namespace: oceansurge
type: Opaque
stringData:
  # IMPORTANT: Replace these placeholders with your actual values
  # DO NOT commit real secrets to version control!
  
  # LaunchDarkly SDK Key - Get from LaunchDarkly dashboard
  ld-sdk-key: "sdk-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  
  # Spot API Token - Get from Spot console
  spot-api-token: "YOUR_SPOT_API_TOKEN_HERE"
  
  # Webhook Secret - Generate a strong random string
  # Example: openssl rand -hex 32
  webhook-secret: "YOUR_WEBHOOK_SECRET_HERE"
  
  # Statsig Server Key (if using Statsig)
  statsig-server-key: "YOUR_STATSIG_SERVER_KEY_HERE"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: oceansurge
type: Opaque
stringData:
  # Use strong passwords!
  # Example: openssl rand -base64 32
  POSTGRES_USER: "oceansurge"
  POSTGRES_PASSWORD: "CHANGE_THIS_TO_A_STRONG_PASSWORD"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flag-config
  namespace: oceansurge
data:
  # Spot Ocean Configuration
  SPOT_CLUSTER_ID: "YOUR_SPOT_CLUSTER_ID"  # e.g., "o-xxxxxxxx"
  SPOT_ACCOUNT_ID: "YOUR_SPOT_ACCOUNT_ID"  # e.g., "act-xxxxxxxx"
  
  # Feature Flag Provider
  FEATURE_FLAG_PROVIDER: "launchdarkly"
  
  # Logging
  LOGGING_PROVIDER: "auto"
  LOG_LEVEL: "INFO"
  
  # Cost Impact Threshold
  COST_IMPACT_THRESHOLD: "0.05"
  
  # Webhook Configuration
  WEBHOOK_ENDPOINT: "/webhook/launchdarkly"
  API_ENDPOINT: "/api/cluster/status"