# Storm Surge E-commerce Demo Application - Fixed Permissions
# Realistic microservices for testing Kubernetes elasticity

---
# Product Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-fixed
  namespace: oceansurge
  labels:
    app: product-catalog-fixed
    tier: backend
    storm-surge.io/component: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-fixed
  template:
    metadata:
      labels:
        app: product-catalog-fixed
        tier: backend
    spec:
      containers:
      - name: product-catalog
        image: nginx:alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: SERVICE_NAME
          value: "product-catalog"
        - name: STORM_SURGE_COMPONENT
          value: "catalog"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: html
        configMap:
          name: product-catalog-html
      - name: nginx-config
        configMap:
          name: nginx-simple-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-fixed-service
  namespace: oceansurge
spec:
  selector:
    app: product-catalog-fixed
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
# Shopping Cart Service (CPU intensive for scaling tests)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-fixed
  namespace: oceansurge
  labels:
    app: shopping-cart-fixed
    tier: backend
    storm-surge.io/component: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-fixed
  template:
    metadata:
      labels:
        app: shopping-cart-fixed
        tier: backend
    spec:
      containers:
      - name: shopping-cart
        image: nginx:alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: SERVICE_NAME
          value: "shopping-cart"
        - name: STORM_SURGE_COMPONENT
          value: "cart"
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: html
        configMap:
          name: shopping-cart-html
      - name: nginx-config
        configMap:
          name: nginx-simple-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-fixed-service
  namespace: oceansurge
spec:
  selector:
    app: shopping-cart-fixed
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP

---
# Frontend Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-fixed
  namespace: oceansurge
  labels:
    app: frontend-fixed
    tier: frontend
    storm-surge.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-fixed
  template:
    metadata:
      labels:
        app: frontend-fixed
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: config
        configMap:
          name: frontend-config-fixed
      - name: html
        configMap:
          name: frontend-html
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-fixed-service
  namespace: oceansurge
spec:
  selector:
    app: frontend-fixed
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

---
# Simple nginx config that works without root
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-simple-config
  namespace: oceansurge
data:
  default.conf: |
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }

---
# Frontend config that works with fixed services
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-fixed
  namespace: oceansurge
data:
  default.conf: |
    upstream shopping-cart {
        server shopping-cart-fixed-service:80;
    }
    upstream product-catalog {
        server product-catalog-fixed-service:80;
    }

    server {
        listen 8080;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }

        location /api/cart/ {
            proxy_pass http://shopping-cart/;
        }

        location /api/products/ {
            proxy_pass http://product-catalog/;
        }
    }

---
# HPA for Shopping Cart
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shopping-cart-fixed-hpa
  namespace: oceansurge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shopping-cart-fixed
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70