apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
- ../base
- finops-controller.yaml

commonLabels:
  app.kubernetes.io/name: storm-surge
  app.kubernetes.io/component: finops
  app.kubernetes.io/part-of: oceansurge
