# KEDA Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    name: keda
    storm-surge.io/component: keda
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
