apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
  - postgresql.yaml
  - redis.yaml

commonLabels:
  app.kubernetes.io/part-of: oceansurge
  app.kubernetes.io/version: dev
  environment: development