apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
  - prometheus.yaml
  - grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: oceansurge
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/version: dev