---
# User Auth API ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-auth-api-config
  namespace: oceansurge
data:
  POSTGRES_HOST: "postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "oceansurge"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "development"

---
# User Auth API Secret
apiVersion: v1
kind: Secret
metadata:
  name: user-auth-api-secret
  namespace: oceansurge
type: Opaque
data:
  POSTGRES_USER: b2NlYW5zdXJnZQ==  # oceansurge
  POSTGRES_PASSWORD: UG9zdGdyZXMxMjM=  # Postgres123
  JWT_SECRET_KEY: b2NlYW5zdXJnZS1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==  # oceansurge-jwt-secret-key-change-in-production

---
# User Auth API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-api
  namespace: oceansurge
  labels:
    app: user-auth-api
    tier: backend
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth-api
  template:
    metadata:
      labels:
        app: user-auth-api
        tier: backend
        component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: user-auth-api
        image: oceansurge/user-auth-api:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: user-auth-api-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-auth-api-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: REDIS_PORT
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: user-auth-api-secret
              key: JWT_SECRET_KEY
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: LOG_LEVEL
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: user-auth-api-config
              key: ENVIRONMENT
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 12

---
# User Auth API Service
apiVersion: v1
kind: Service
metadata:
  name: user-auth-api
  namespace: oceansurge
  labels:
    app: user-auth-api
spec:
  selector:
    app: user-auth-api
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP