apiVersion: v1
kind: ConfigMap
metadata:
  name: storm-surge-frontend-config
  namespace: oceansurge
  labels:
    app: storm-surge-frontend
    component: frontend
data:
  # Environment-specific configuration
  REACT_APP_API_BASE_URL: "/api"
  REACT_APP_WS_URL: "/socket.io"
  REACT_APP_VERSION: "1.0.0"
  REACT_APP_ENVIRONMENT: "production"

  # Feature flags for the frontend
  REACT_APP_ENABLE_ANALYTICS: "true"
  REACT_APP_ENABLE_REALTIME: "true"
  REACT_APP_ENABLE_COST_TRACKING: "true"
