apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: storm-surge-frontend
  namespace: oceansurge

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/name: storm-surge-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: storm-surge

images:
- name: storm-surge-frontend
  newTag: latest

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: storm-surge-frontend
      namespace: oceansurge
    spec:
      template:
        spec:
          containers:
          - name: frontend
            envFrom:
            - configMapRef:
                name: storm-surge-frontend-config
  target:
    kind: Deployment
    name: storm-surge-frontend
