apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oceansurge

resources:
  # Core infrastructure
  - ../base/namespace.yaml
  
  # Databases
  - ../databases/
  
  # Messaging
  - ../messaging/rabbitmq.yaml
  
  # Services
  - ../services/product-catalog/deployment.yaml
  - ../services/shopping-cart/deployment.yaml  
  - ../services/user-auth/deployment.yaml
  
  # Legacy frontend (updated to use new APIs)
  - ../base/services.yaml
  - frontend-deployment.yaml
  
  # Monitoring
  - ../monitoring/
  
  # Middleware
  - ../middleware/
  
  # FinOps
  - ../finops/

commonLabels:
  app.kubernetes.io/part-of: oceansurge
  app.kubernetes.io/version: dev
  environment: development

images:
  # These would be built and pushed to a registry
  - name: oceansurge/product-catalog-api
    newTag: dev
  - name: oceansurge/shopping-cart-api
    newTag: dev
  - name: oceansurge/user-auth-api
    newTag: dev

patchesStrategicMerge:
  # Update frontend to proxy to new APIs
  - frontend-config-patch.yaml