apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storm-surge-prod

# Core resources
resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

# Apply security patches
patches:
  - path: security-patch.yaml
    target:
      kind: Deployment
      name: storm-surge-middleware

labels:
  - pairs:
      app.kubernetes.io/name: storm-surge-core
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/managed-by: kustomize