apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: storm-surge-prod

resources:
  - namespace.yaml
  - ../middleware/configmap-minimal.yaml
  - ../middleware/deployment-minimal.yaml
  - ../middleware/service-minimal.yaml
  - ../middleware/secrets-minimal.yaml
  - ../security/production-security-hardening.yaml

# Add security patches
patchesStrategicMerge:
  - security-patch.yaml

commonLabels:
  app.kubernetes.io/name: storm-surge-core
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize