name: 🚀 Create GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release from Tag
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🧾 Read CHANGELOG for version notes
        id: changelog
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          NOTES=$(awk "/^## ${TAG}/,/^## v/" CHANGELOG.md | sed '$d')
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 🚀 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
